export const CATEGORY_LABELS_CLIENT: Record<string, string> = {
  backend: "Backend & APIs",
  dsa: "Data Structures & Algorithms",
  design_patterns: "LLD & Design Patterns",
  dbms: "DBMS & SQL",
  os: "Operating Systems",
  networking: "Computer Networks",
  system_design: "Distributed Systems & System Design",
  cloud: "Cloud (AWS/Azure/GCP)",
  devops: "DevOps, CI/CD & Observability",
  kubernetes: "Containers & Kubernetes",
  frontend: "Frontend",
  behavioral: "Leadership & Behavioral",
  resume: "Resume Deep-Dive",
  daily: "30-Day Planner",
  extras: "Extras",
  projects: "Projects",
  security: "Security",
};
